# helm/ai-application/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: llm-app-secrets
  namespace: default  # Replace with your namespace if different
type: Opaque
data:
  mongodbRootPassword: {{ "your-mongodb-root-password" | b64enc }}
  postgresqlPassword: {{ "your-postgresql-password" | b64enc }}
  clientId: {{ "your-auth0-client-id" | b64enc }}
  clientSecret: {{ "your-auth0-client-secret" | b64enc }}
  grafanaAdminPassword: {{ "your-grafana-admin-password" | b64enc }}
  openaiApiKey: {{ "your-openai-api-key" | b64enc }}
  taverlyApiKey: {{ "your-taverly-api-key" | b64enc }}
  langchainApiKey: {{ "your-langchain-api-key" | b64enc }}
  anthropicApiKey: {{ "your-anthropic-api-key" | b64enc }}

