# helm/ai-application/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: llm-app-secrets
  namespace: default  # Replace with your namespace if different
type: Opaque
data:
  # Base64 encoded secrets for MongoDB, PostgreSQL, Weaviate, Neo4j, and MLflow
  mongodbRootPassword: {{ "your-mongodb-root-password" | b64enc }}
  postgresqlPassword: {{ "your-postgresql-password" | b64enc }}
  weaviateApiKey: {{ "your-weaviate-api-key" | b64enc }}
  neo4jPassword: {{ "your-neo4j-password" | b64enc }}

  # Auth0 secrets
  clientId: {{ "your-auth0-client-id" | b64enc }}
  clientSecret: {{ "your-auth0-client-secret" | b64enc }}
  
  # Grafana admin password
  grafanaAdminPassword: {{ "your-grafana-admin-password" | b64enc }}
  
  # MLflow Tracking password
  mlflowTrackingPassword: {{ "your-mlflow-tracking-password" | b64enc }}

  # API keys for external services
  openaiApiKey: {{ "your-openai-api-key" | b64enc }}
  taverlyApiKey: {{ "your-taverly-api-key" | b64enc }}
  langchainApiKey: {{ "your-langchain-api-key" | b64enc }}
  anthropicApiKey: {{ "your-anthropic-api-key" | b64enc }}
