# helm/ai-application/templates/service-frontend.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: llm-app
    component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: llm-app
    component: frontend
  ports:
    - name: http
      port: 80             # Service port exposed outside the cluster
      targetPort: 3000      # Port on the frontend container
