# helm/ai-application/templates/service-grafana.yaml
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: llm-app
    component: grafana
spec:
  type: {{ .Values.logging.grafana.service.type }}
  selector:
    app: llm-app
    component: grafana
  ports:
    - name: http
      port: 3000          # Service port exposed outside the cluster
      targetPort: 3000     # Port on the Grafana container
