# helm/ai-application/templates/service-weaviate.yaml
apiVersion: v1
kind: Service
metadata:
  name: weaviate
  labels:
    app: llm-app
    component: weaviate
spec:
  type: {{ .Values.weaviate.service.type }}
  selector:
    app: llm-app
    component: weaviate
  ports:
    - name: http
      port: 8080         # Service port exposed within or outside the cluster
      targetPort: 8080    # Port on the Weaviate container
